import type {
  AppStoresDataset,
  CaseStatus,
  CaseType,
  ChecklistItemStatus,
  DeclarationDecision,
  DeclarationStatus,
  FeatureAvailability,
  ReadinessGate,
  StoreId,
  SubmissionStatus,
} from "@/lib/app-stores/types";

export const APP_STORES_DATASET: AppStoresDataset = {
  generatedAt: "2026-03-05T16:10:00Z",
  releaseTrains: [
    {
      id: "train-ios-4.7.0",
      store: "apple",
      platform: "iOS",
      version: "4.7.0",
      buildNumber: "523",
      status: "in_review",
      targetDate: "2026-03-11",
      owner: "Wallet Eng",
      blockers: ["Awaiting Apple reviewer response on metadata phrasing for swap disclosure."],
    },
    {
      id: "train-android-4.7.0",
      store: "google",
      platform: "Android",
      version: "4.7.0",
      buildNumber: "290",
      status: "developer_action_required",
      targetDate: "2026-03-12",
      owner: "Android Eng",
      blockers: ["Google Financial Features declaration update overdue for 3 impacted regions."],
    },
  ],
  submissions: [
    {
      id: "sub-google-4.7.0-290",
      store: "google",
      platform: "Android",
      appVersion: "4.7.0",
      buildNumber: "290",
      track: "Production",
      submissionDate: "2026-03-03T15:10:00Z",
      status: "developer_action_required",
      blockers: [
        "Financial features declaration is overdue for DE, FR, and NL.",
        "Policy/legal sign-off missing for EU limited availability posture.",
      ],
      ownerEngineering: "Alex M.",
      approverPolicyLegal: "Pending",
      consoleUrl: "https://play.google.com/console",
      checklistSnapshotUrl: "https://zodldashboard.com/app-stores/submissions?submission=sub-google-4.7.0-290#readiness",
      evidenceBundleUrl: "https://zodldashboard.com/app-stores/evidence-vault?bundle=bundle-google-470",
      releaseNotesUrl: "https://github.com/paulbrigner/zodldashboard/releases/tag/v4.7.0",
      whatChanged:
        "Swaps copy updated and geofencing checks tightened for high-risk regions; new compliance language added to onboarding.",
      declarationsTouched: ["decl-google-financial-de", "decl-google-financial-fr", "decl-google-financial-nl"],
      assetsUsed: [
        "Android screenshots set v4.7.0",
        "Store listing short/long descriptions v4.7.0",
        "Financial features declaration answer set v3",
      ],
      reviewerCaseId: "case-google-2217",
      outcome: "Blocked pending declaration updates and policy sign-off.",
      lessonsLearned: "Treat declaration updates as a hard pre-submit gate when geofencing or swap UX changes are included.",
      readinessGate: "red",
      checklist: [
        {
          id: "release-notes",
          label: "Release notes finalized",
          status: "done",
        },
        {
          id: "feature-claim-update",
          label: "Feature-to-Claim Matrix updated for changed features",
          status: "done",
        },
        {
          id: "google-decl-review",
          label: "Google declarations reviewed for impacted regions",
          status: "blocked",
          note: "DE/FR/NL overdue.",
        },
        {
          id: "apple-disclosure-review",
          label: "Apple disclosures reviewed",
          status: "done",
        },
        {
          id: "fees-iap-analysis",
          label: "Fees/IAP analysis attached",
          status: "needs_attention",
          note: "Needs legal acknowledgement for EU copy updates.",
        },
        {
          id: "sanctions-confirm",
          label: "Sanctions/geofencing posture confirmed",
          status: "needs_attention",
          note: "Policy approver pending.",
        },
        {
          id: "internal-approvals",
          label: "Internal approvals (Eng + Policy + Legal)",
          status: "blocked",
        },
      ],
    },
    {
      id: "sub-apple-4.7.0-523",
      store: "apple",
      platform: "iOS",
      appVersion: "4.7.0",
      buildNumber: "523",
      track: "Production",
      submissionDate: "2026-03-04T09:25:00Z",
      status: "in_review",
      blockers: ["Reviewer asked for clarification on non-custodial language in app description."],
      ownerEngineering: "Maya R.",
      approverPolicyLegal: "Priya S.",
      consoleUrl: "https://appstoreconnect.apple.com",
      checklistSnapshotUrl: "https://zodldashboard.com/app-stores/submissions?submission=sub-apple-4.7.0-523#readiness",
      evidenceBundleUrl: "https://zodldashboard.com/app-stores/evidence-vault?bundle=bundle-apple-470",
      releaseNotesUrl: "https://github.com/paulbrigner/zodldashboard/releases/tag/v4.7.0-ios",
      whatChanged:
        "Updated privacy wording and added governance entrypoint copy; no custody model change.",
      declarationsTouched: ["decl-apple-payments-all", "decl-apple-restricted-all", "decl-apple-dsa-eu"],
      assetsUsed: ["iOS screenshots set v4.7.0", "App privacy text revision 2026-03-04"],
      reviewerCaseId: "case-apple-772",
      outcome: "Pending review.",
      lessonsLearned: "Pre-approve alternate non-custodial phrasing to respond quickly when reviewer asks for clarification.",
      readinessGate: "yellow",
      checklist: [
        {
          id: "release-notes",
          label: "Release notes finalized",
          status: "done",
        },
        {
          id: "feature-claim-update",
          label: "Feature-to-Claim Matrix updated for changed features",
          status: "done",
        },
        {
          id: "google-decl-review",
          label: "Google declarations reviewed for impacted regions",
          status: "done",
        },
        {
          id: "apple-disclosure-review",
          label: "Apple disclosures reviewed",
          status: "done",
        },
        {
          id: "apple-dsa-review",
          label: "Apple DSA trader/non-trader declaration reviewed",
          status: "done",
          note: "Current response: non-trader / no EU trader distribution declaration.",
        },
        {
          id: "fees-iap-analysis",
          label: "Fees/IAP analysis attached",
          status: "needs_attention",
          note: "No IAP used; rationale added but legal comment requested.",
        },
        {
          id: "sanctions-confirm",
          label: "Sanctions/geofencing posture confirmed",
          status: "done",
        },
        {
          id: "internal-approvals",
          label: "Internal approvals (Eng + Policy + Legal)",
          status: "done",
        },
      ],
    },
    {
      id: "sub-google-4.6.2-284",
      store: "google",
      platform: "Android",
      appVersion: "4.6.2",
      buildNumber: "284",
      track: "Production",
      submissionDate: "2026-02-18T11:35:00Z",
      status: "approved",
      blockers: [],
      ownerEngineering: "Alex M.",
      approverPolicyLegal: "Priya S.",
      consoleUrl: "https://play.google.com/console",
      checklistSnapshotUrl: "https://zodldashboard.com/app-stores/submissions?submission=sub-google-4.6.2-284#readiness",
      evidenceBundleUrl: "https://zodldashboard.com/app-stores/evidence-vault?bundle=bundle-google-462",
      releaseNotesUrl: "https://github.com/paulbrigner/zodldashboard/releases/tag/v4.6.2",
      whatChanged: "Minor bug fixes and telemetry text clarification.",
      declarationsTouched: ["decl-google-financial-us", "decl-google-financial-gb", "decl-google-financial-ca"],
      assetsUsed: ["Android screenshots set v4.6.2", "Data safety disclosure rev2"],
      outcome: "Approved with no follow-up actions.",
      lessonsLearned: "Re-using statement pack copy reduced reviewer back-and-forth.",
      readinessGate: "green",
      checklist: [
        { id: "release-notes", label: "Release notes finalized", status: "done" },
        {
          id: "feature-claim-update",
          label: "Feature-to-Claim Matrix updated for changed features",
          status: "done",
        },
        {
          id: "google-decl-review",
          label: "Google declarations reviewed for impacted regions",
          status: "done",
        },
        { id: "apple-disclosure-review", label: "Apple disclosures reviewed", status: "done" },
        { id: "fees-iap-analysis", label: "Fees/IAP analysis attached", status: "done" },
        { id: "sanctions-confirm", label: "Sanctions/geofencing posture confirmed", status: "done" },
        { id: "internal-approvals", label: "Internal approvals (Eng + Policy + Legal)", status: "done" },
      ],
    },
  ],
  declarations: [
    {
      id: "decl-google-financial-de",
      store: "google",
      declarationType: "Financial features declaration",
      scope: "per_region",
      regionCode: "DE",
      regionLabel: "Germany",
      status: "overdue",
      effectiveDate: "2025-12-01",
      updateByDate: "2026-03-01",
      requiresDocs: "yes",
      internalDetermination: "depends",
      notes: "Needs external counsel confirmation for limited swap availability statements.",
      answersSnapshot: "Certification started; pending confirmation on regional restrictions and disclosures.",
      rationale: "Feature availability differs by region; declaration must mirror geofencing behavior.",
      sourceLinks: ["Internal legal memo #44", "Counsel thread: DE scope 2026-02-27"],
    },
    {
      id: "decl-google-financial-fr",
      store: "google",
      declarationType: "Financial features declaration",
      scope: "per_region",
      regionCode: "FR",
      regionLabel: "France",
      status: "overdue",
      effectiveDate: "2025-12-01",
      updateByDate: "2026-03-01",
      requiresDocs: "yes",
      internalDetermination: "depends",
      notes: "Mirrors DE requirement state.",
      answersSnapshot: "Draft answers entered; awaiting legal sign-off.",
      rationale: "Need consistent statements for non-custodial wallet with limited feature set.",
      sourceLinks: ["Internal legal memo #44", "Policy note: FR declaration map"],
    },
    {
      id: "decl-google-financial-nl",
      store: "google",
      declarationType: "Financial features declaration",
      scope: "per_region",
      regionCode: "NL",
      regionLabel: "Netherlands",
      status: "in_progress",
      effectiveDate: "2025-12-01",
      updateByDate: "2026-03-08",
      requiresDocs: "unknown",
      internalDetermination: "unknown",
      notes: "Evidence package assembled; awaiting determination.",
      answersSnapshot: "Questionnaire in progress; docs upload requirement unresolved.",
      rationale: "Need counsel guidance before filing a definitive response.",
      sourceLinks: ["Counsel request ticket #129"],
    },
    {
      id: "decl-google-financial-us",
      store: "google",
      declarationType: "Financial features declaration",
      scope: "per_region",
      regionCode: "US",
      regionLabel: "United States",
      status: "completed",
      effectiveDate: "2025-12-01",
      updateByDate: "2026-05-01",
      requiresDocs: "no",
      internalDetermination: "not_required",
      signOffBy: "Priya S.",
      signOffDate: "2026-02-14",
      notes: "Current posture validated against non-custodial architecture memo.",
      answersSnapshot: "Completed and submitted in Play Console.",
      rationale: "No custodial handling; wallet remains user-controlled.",
      sourceLinks: ["Architecture note: non-custodial keys"],
    },
    {
      id: "decl-apple-payments-all",
      store: "apple",
      declarationType: "Payments and value transfer disclosure",
      scope: "all_regions",
      regionCode: "ALL",
      regionLabel: "All regions",
      status: "completed",
      effectiveDate: "2026-02-01",
      updateByDate: "2026-04-15",
      requiresDocs: "no",
      internalDetermination: "not_required",
      signOffBy: "Priya S.",
      signOffDate: "2026-02-20",
      notes: "Aligned to non-custodial wallet language and no in-app purchase policy.",
      answersSnapshot: "Completed questionnaire responses saved in ASC.",
      rationale: "No direct fiat processing, no custodial account handling.",
      sourceLinks: ["ASC screenshot set 2026-02-20"],
    },
    {
      id: "decl-apple-restricted-all",
      store: "apple",
      declarationType: "Restricted services attestation",
      scope: "all_regions",
      regionCode: "ALL",
      regionLabel: "All regions",
      status: "needs_update",
      effectiveDate: "2026-01-15",
      updateByDate: "2026-03-09",
      requiresDocs: "unknown",
      internalDetermination: "depends",
      notes: "Needs refresh after swap UX wording update.",
      answersSnapshot: "Prior response references old fee disclosure language.",
      rationale: "Store metadata and declaration wording must stay synchronized.",
      sourceLinks: ["Reviewer note case-apple-772"],
    },
    {
      id: "decl-apple-dsa-eu",
      store: "apple",
      declarationType: "Digital Services Act (DSA) trader status",
      scope: "per_region",
      regionCode: "EU",
      regionLabel: "European Union",
      status: "completed",
      effectiveDate: "2026-03-05",
      updateByDate: "2026-06-01",
      requiresDocs: "no",
      internalDetermination: "not_required",
      signOffBy: "Priya S.",
      signOffDate: "2026-03-05",
      notes: "Current posture captured from App Store Connect DSA form.",
      answersSnapshot:
        "Selected: \"I'm not a trader under the DSA or I don't plan to distribute in the EU.\"",
      rationale: "Current app distribution plan does not represent trader distribution in the EU.",
      sourceLinks: ["ASC DSA screenshot capture 2026-03-05", "Internal policy note DSA-2026-03-05"],
      questionPrompt:
        "Specify if you'll distribute any content in the EU in the capacity of a trader or non-trader.",
      selectedResponse: "I'm not a trader under the DSA or I don't plan to distribute in the EU",
      responseOptions: [
        "I'm a trader under the DSA",
        "I'm not a trader under the DSA or I don't plan to distribute in the EU",
      ],
      responseImpact:
        "No trader contact details are displayed on the App Store product page under current selection.",
    },
  ],
  featureMatrix: [
    {
      featureId: "feature-shielded-send",
      featureName: "Shielded send/receive",
      description: "Core private send/receive flow for user-controlled wallet addresses.",
      uiSurfaces: ["Send screen", "Receive screen", "Transaction history"],
      dataTouched: ["Wallet addresses", "Transaction metadata", "Device telemetry (minimal)"],
      dependencies: ["Lightwalletd RPC", "Mobile secure enclave"],
      providesCryptoFeatures: true,
      custodyModel: "non_custodial",
      swapsMode: "none",
      feesModel: "Network fee only; no platform fee.",
      fiatOnOffRamp: false,
      stakingYield: false,
      kycCollection: false,
      geofencingSanctionsControls: "Country and sanctions list checks at feature entrypoint.",
      financialAdviceAvoidanceLanguage: "App does not provide investment advice.",
      declarationLinks: ["decl-google-financial-us", "decl-apple-payments-all"],
      evidenceLinks: ["evidence-arch-01", "evidence-policy-03"],
    },
    {
      featureId: "feature-swaps",
      featureName: "Swaps",
      description: "Token swap flow with region-scoped availability controls.",
      uiSurfaces: ["Swap tab", "Quote confirmation", "Disclosures modal"],
      dataTouched: ["Wallet addresses", "Quote request payload", "Region signal"],
      dependencies: ["Swap provider API", "Pricing service"],
      providesCryptoFeatures: true,
      custodyModel: "non_custodial",
      swapsMode: "dex_aggregation",
      feesModel: "Spread + potential affiliate fee disclosure.",
      fiatOnOffRamp: false,
      stakingYield: false,
      kycCollection: false,
      geofencingSanctionsControls: "Feature-level disable list by jurisdiction; sanctions denylist enforcement.",
      financialAdviceAvoidanceLanguage: "Quotes are informational and not financial advice.",
      declarationLinks: ["decl-google-financial-de", "decl-google-financial-fr", "decl-apple-restricted-all"],
      evidenceLinks: ["evidence-legal-07", "evidence-sanctions-02", "evidence-console-11"],
    },
    {
      featureId: "feature-governance",
      featureName: "Governance voting",
      description: "In-wallet governance voting with optional hardware signing.",
      uiSurfaces: ["Governance tab", "Proposal detail", "Vote confirmation"],
      dataTouched: ["On-chain vote payload", "Wallet signing intent"],
      dependencies: ["Governance API", "Keystone integration"],
      providesCryptoFeatures: true,
      custodyModel: "non_custodial",
      swapsMode: "none",
      feesModel: "No app fee; network fee may apply.",
      fiatOnOffRamp: false,
      stakingYield: false,
      kycCollection: false,
      geofencingSanctionsControls: "Global availability with sanctions checks.",
      financialAdviceAvoidanceLanguage: "Governance content is informational and not financial advice.",
      declarationLinks: ["decl-google-financial-us", "decl-apple-payments-all"],
      evidenceLinks: ["evidence-arch-01", "evidence-policy-03"],
    },
  ],
  jurisdictionPosture: [
    {
      featureId: "feature-swaps",
      regionCode: "US",
      regionLabel: "United States",
      availability: "limited",
      rationale: "Enabled only where partner coverage and internal policy criteria are satisfied.",
    },
    {
      featureId: "feature-swaps",
      regionCode: "DE",
      regionLabel: "Germany",
      availability: "under_review",
      rationale: "Awaiting declaration completion and legal sign-off.",
    },
    {
      featureId: "feature-swaps",
      regionCode: "FR",
      regionLabel: "France",
      availability: "under_review",
      rationale: "Awaiting declaration completion and legal sign-off.",
    },
    {
      featureId: "feature-shielded-send",
      regionCode: "ALL",
      regionLabel: "All supported regions",
      availability: "allowed",
      rationale: "Core wallet functionality aligned with current policy posture.",
    },
  ],
  reviewerCases: [
    {
      id: "case-google-2217",
      store: "google",
      caseType: "policy_inquiry",
      severity: "high",
      status: "awaiting_response",
      openedAt: "2026-03-03T18:25:00Z",
      lastActivityAt: "2026-03-05T12:40:00Z",
      owner: "Policy Ops",
      affectedVersions: ["Android 4.7.0 (290)"],
      policyCitations: ["Financial products and services declaration policy"],
      attachments: ["Google policy email 2026-03-05", "Play Console screenshot #ff-de-fr"],
      resolutionNotes: "Draft response prepared; blocked on legal approval.",
      playbookTag: "crypto-swaps",
    },
    {
      id: "case-apple-772",
      store: "apple",
      caseType: "warning",
      severity: "medium",
      status: "open",
      openedAt: "2026-03-04T14:10:00Z",
      lastActivityAt: "2026-03-05T11:22:00Z",
      owner: "Release Manager",
      affectedVersions: ["iOS 4.7.0 (523)"],
      policyCitations: ["App Store Review Guideline 3.1", "Guideline 5.1 transparency guidance"],
      attachments: ["ASC reviewer note screenshot", "Metadata copy diff"],
      resolutionNotes: "Need alternate non-custodial wording before responding.",
      playbookTag: "fees-iap",
    },
    {
      id: "case-google-2174",
      store: "google",
      caseType: "reinstatement",
      severity: "low",
      status: "resolved",
      openedAt: "2026-02-16T08:00:00Z",
      lastActivityAt: "2026-02-18T16:05:00Z",
      owner: "Policy Ops",
      affectedVersions: ["Android 4.6.2 (284)"],
      policyCitations: ["Metadata consistency policy"],
      attachments: ["Response draft v2", "Approval screenshot"],
      resolutionNotes: "Resolved after metadata correction and re-review.",
      playbookTag: "metadata",
    },
  ],
  caseEvents: [
    {
      id: "event-case-google-2217-1",
      caseId: "case-google-2217",
      timestamp: "2026-03-03T18:25:00Z",
      author: "Google Reviewer",
      channel: "Play Console",
      message: "Please update financial features declaration for affected regions before review can proceed.",
    },
    {
      id: "event-case-google-2217-2",
      caseId: "case-google-2217",
      timestamp: "2026-03-04T10:14:00Z",
      author: "Policy Ops",
      channel: "Internal Note",
      message: "Mapped impacted regions to DE/FR/NL and requested legal confirmation.",
    },
    {
      id: "event-case-google-2217-3",
      caseId: "case-google-2217",
      timestamp: "2026-03-05T12:40:00Z",
      author: "Legal",
      channel: "Email",
      message: "Provided draft language; approval pending final sanctions wording alignment.",
    },
    {
      id: "event-case-apple-772-1",
      caseId: "case-apple-772",
      timestamp: "2026-03-04T14:10:00Z",
      author: "Apple Reviewer",
      channel: "App Store Connect",
      message: "Clarify non-custodial wallet language in metadata and disclosure text.",
    },
    {
      id: "event-case-apple-772-2",
      caseId: "case-apple-772",
      timestamp: "2026-03-05T11:22:00Z",
      author: "Release Manager",
      channel: "Internal Note",
      message: "Prepared alternate copy set and requested policy approval.",
    },
  ],
  evidenceItems: [
    {
      id: "evidence-arch-01",
      title: "Non-custodial architecture note",
      evidenceType: "architecture_note",
      jurisdictions: ["Global"],
      features: ["Shielded send/receive", "Governance voting"],
      stores: ["apple", "google"],
      effectiveFrom: "2026-01-05",
      owner: "Engineering",
      approver: "Policy",
      confidentiality: "internal",
      storageRef: "s3://zodl-evidence/architecture/non-custodial-v3.pdf",
    },
    {
      id: "evidence-legal-07",
      title: "EU swap availability counsel memo",
      evidenceType: "legal_memo",
      jurisdictions: ["Germany", "France", "Netherlands"],
      features: ["Swaps"],
      stores: ["google"],
      effectiveFrom: "2026-02-27",
      owner: "Legal",
      approver: "GC",
      confidentiality: "legal_privileged",
      storageRef: "s3://zodl-evidence/legal/eu-swaps-memo-2026-02-27.pdf",
    },
    {
      id: "evidence-sanctions-02",
      title: "Sanctions/geofencing control design",
      evidenceType: "sanctions_control",
      jurisdictions: ["Global"],
      features: ["Swaps", "Shielded send/receive"],
      stores: ["apple", "google"],
      effectiveFrom: "2026-02-15",
      owner: "Policy Ops",
      approver: "Legal",
      confidentiality: "restricted",
      storageRef: "s3://zodl-evidence/policy/sanctions-geofencing-v2.md",
    },
    {
      id: "evidence-console-11",
      title: "Play Console financial features screenshot set",
      evidenceType: "console_screenshot",
      jurisdictions: ["Germany", "France", "Netherlands"],
      features: ["Swaps"],
      stores: ["google"],
      effectiveFrom: "2026-03-05",
      owner: "Policy Ops",
      approver: "Policy Lead",
      confidentiality: "internal",
      storageRef: "s3://zodl-evidence/console/google-financial-features-2026-03-05.zip",
    },
    {
      id: "evidence-console-apple-dsa-01",
      title: "App Store Connect DSA trader status screenshot",
      evidenceType: "console_screenshot",
      jurisdictions: ["European Union"],
      features: ["App store compliance metadata"],
      stores: ["apple"],
      effectiveFrom: "2026-03-05",
      owner: "Policy Ops",
      approver: "Legal",
      confidentiality: "internal",
      storageRef: "s3://zodl-evidence/console/apple-dsa-trader-status-2026-03-05.png",
    },
    {
      id: "evidence-policy-03",
      title: "Financial advice avoidance language policy",
      evidenceType: "policy_analysis",
      jurisdictions: ["Global"],
      features: ["Shielded send/receive", "Swaps", "Governance voting"],
      stores: ["apple", "google"],
      effectiveFrom: "2026-02-10",
      owner: "Policy Ops",
      approver: "Legal",
      confidentiality: "internal",
      storageRef: "s3://zodl-evidence/policy/financial-advice-avoidance-v1.md",
    },
  ],
  evidenceBundles: [
    {
      id: "bundle-google-470",
      name: "Google 4.7.0 submission evidence bundle",
      submissionId: "sub-google-4.7.0-290",
      createdAt: "2026-03-05T12:50:00Z",
      createdBy: "Policy Ops",
      evidenceItemIds: ["evidence-legal-07", "evidence-sanctions-02", "evidence-console-11"],
      notes: "Prepared for declaration update response and reviewer follow-up.",
    },
    {
      id: "bundle-apple-470",
      name: "Apple 4.7.0 submission evidence bundle",
      submissionId: "sub-apple-4.7.0-523",
      createdAt: "2026-03-04T10:00:00Z",
      createdBy: "Release Manager",
      evidenceItemIds: ["evidence-arch-01", "evidence-policy-03", "evidence-console-apple-dsa-01"],
      notes: "Used for non-custodial and disclosures consistency backup.",
    },
    {
      id: "bundle-google-462",
      name: "Google 4.6.2 approved evidence bundle",
      submissionId: "sub-google-4.6.2-284",
      createdAt: "2026-02-18T10:40:00Z",
      createdBy: "Policy Ops",
      evidenceItemIds: ["evidence-arch-01", "evidence-policy-03"],
      notes: "Reference bundle from last successful production run.",
    },
  ],
  featureChanges: [
    {
      id: "fc-470-swaps-copy",
      releaseVersion: "4.7.0",
      featureName: "Swaps",
      summary: "Updated disclosure copy and geofencing checks for EU regions.",
      reviewed: false,
      riskFlags: ["declaration-impact", "regional-availability-change"],
    },
    {
      id: "fc-470-governance-copy",
      releaseVersion: "4.7.0",
      featureName: "Governance voting",
      summary: "Added onboarding text clarifying participation and privacy properties.",
      reviewed: true,
      riskFlags: [],
    },
    {
      id: "fc-462-telemetry",
      releaseVersion: "4.6.2",
      featureName: "Telemetry wording",
      summary: "Clarified privacy description in settings and store metadata.",
      reviewed: true,
      riskFlags: ["privacy-copy-change"],
    },
  ],
  integrationStatus: {
    githubReleases: "planned",
    slackAlerts: "planned",
    consoleIngestion: "manual_only",
  },
};

export const STORE_LABELS: Record<StoreId, string> = {
  apple: "Apple",
  google: "Google Play",
};

export const SUBMISSION_STATUS_LABELS: Record<SubmissionStatus, string> = {
  draft: "Draft",
  submitted: "Submitted",
  in_review: "In review",
  approved: "Approved",
  rejected: "Rejected",
  removed: "Removed",
  developer_action_required: "Developer action required",
};

export const READINESS_GATE_LABELS: Record<ReadinessGate, string> = {
  green: "Green",
  yellow: "Yellow",
  red: "Red",
};

export const CHECKLIST_STATUS_LABELS: Record<ChecklistItemStatus, string> = {
  done: "Done",
  needs_attention: "Needs attention",
  blocked: "Blocked",
};

export const DECLARATION_STATUS_LABELS: Record<DeclarationStatus, string> = {
  not_started: "Not started",
  in_progress: "In progress",
  completed: "Completed",
  needs_update: "Needs update",
  overdue: "Overdue",
};

export const DECLARATION_DECISION_LABELS: Record<DeclarationDecision, string> = {
  required: "Required",
  not_required: "Not required",
  depends: "Depends",
  unknown: "Unknown",
  blocked: "Blocked",
};

export const CASE_STATUS_LABELS: Record<CaseStatus, string> = {
  open: "Open",
  awaiting_response: "Awaiting response",
  resolved: "Resolved",
};

export const CASE_TYPE_LABELS: Record<CaseType, string> = {
  rejection: "Rejection",
  warning: "Warning",
  policy_inquiry: "Policy inquiry",
  escalation: "Escalation",
  reinstatement: "Reinstatement",
};

export const FEATURE_AVAILABILITY_LABELS: Record<FeatureAvailability, string> = {
  allowed: "Allowed",
  disabled: "Disabled",
  limited: "Limited",
  under_review: "Under review",
};

export function getAppStoresDataset(): AppStoresDataset {
  return APP_STORES_DATASET;
}
